### ISSUE TITLE
Clarify All user operations blocked

### ISSUE THREAD

**Issue by jeffmcaffer** [peterkhayes/rolling-rate-limiter#15]
First, I quite like the design and implementation.  Thanks!  The doc mentions

> Note: if an action is blocked, it is still added to the set. This means that if a user is continually attempting actions more quickly than the allowed rate, all of their actions will be blocked until they pause or slow their requests.

Can you give an example of the effect of this?  

In our case we are looking to limit outbound calls so as to not abuse a service.  There are many agents doing calls and they should be limited in aggregate to N calls / second.  Our first try using this library was for each agent to call the limiter and if no limit is available, put the request on an in-memory queue and delay timeLeft ms.  Each agent has many (e..g, 40 processing "loops") so there could be as many as 40 ratelimit attempts in flight. This sort of worked but as soon as one of the loops got ratelimited, all the others seemed to get into a synchronized delay/ratelimit cycle.  

The synchronizing makes sense as the timeLeft result for a given interval will indicate the same expiry time for all callers in an interval.  That is, they will all wake up and retry their ratelimit call at about the same time.  I'm guessing that somehow the noted characteristic is coming to play and somehow the ratelimit exhaustion is carrying over into the next time interval.  Does that make sense?

**Comment by peterkhayes** [comment]
It's hard to know exactly what's happening in your case, but what I mean is that every time an action is attempted, it counts as an action.  So, if the rate is 4 actions per 5 seconds, and we attempt an action every second, we could have the following sequence:
```
t0: Action permitted (3 remaining)
t1: Action permitted (2 remaining)
t2: Action permitted (1 remaining)
t3: Action permitted (0 remaining)
t4: Action blocked (still 0 remaining)
t5: Action blocked (still 0 remaining)
etc...
```

The only way to be allowed more actions is to stop attempting them. If the user waiting one second without making a request, they'd be allowed to make another action.

**Comment by nonplus** [comment]
I think we can avoid starvation like this by by removing the "unused" key from the set when our request is rejected.  I.e.
```javascript
if (tooManyInInterval || timeSinceLastRequest < minDifference) {
    redis.zrem(key, now);
    ...
    remaining = -1;
} else {
    remaining = maxInInterval - userSet.length - 1;
    result = 0;
}
```
This shouldn't cause problems with atomicity or race conditions.  Making this change gives me the following run sequence:
```
t0: Action permitted (3 remaining), timeLeft 0)
t1: Action permitted (2 remaining), timeLeft 0)
t2: Action permitted (1 remaining), timeLeft 0)
t3: Action permitted (0 remaining), timeLeft 0)
t4: Action blocked (still -1 remaining, timeLeft 977)
t5: Action permitted (0 remaining), timeLeft 0)
t6: Action permitted (0 remaining), timeLeft 0)
t7: Action permitted (0 remaining), timeLeft 0)
t8: Action permitted (0 remaining), timeLeft 0)
t9: Action blocked (still -1 remaining, timeLeft 983)
t10: Action permitted (0 remaining), timeLeft 0)
t11: Action permitted (0 remaining), timeLeft 0)
```

**Comment by jeffmcaffer** [comment]
The remaining count in the output is 0 after the first exhaustion.  In my particular case the remaining count is not a huge factor but others may be using it.

**Comment by nonplus** [comment]
FWIW, I didn't change the behavior of the `remaining` count, the existing code `returns -1` on exhaustion.  I don't think @peterkhayes example above was from an actual run...

**Comment by jeffmcaffer** [comment]
@nonplus I was referring to your output.  t5-t7 have "0 remaining".  That should be 3, 2, 1 respectively.  Otherwise that value (remaining) is not reporting the right value.

**Comment by nonplus** [comment]
Oh, I see.  No, it's actually reporting the correct values.
* t0-t3 drained the original bucket.
* At t4, activity got blocked because bucket was empty
* By t5, one more item was added into the bucked and then was drained by activity (hence 0 remaining)
* By t6, one more item was added into the bucked and then was drained by activity (hence 0 remaining)
* ...
* At t9, activity got blocked because bucket was still empty

**Comment by janober** [comment]
Sorry I am a little bit confused. Because I did run into the same issue. After I found and read this issue, it sounded like it should work now. However I get the following result with the current version (0.1.5):
```
t0 -> OK       (timeLeft: 0 | actionsLeft: 0)
t1 -> BLOCK    (timeLeft: 3995 | actionsLeft: -1)
t2 -> BLOCK    (timeLeft: 2994 | actionsLeft: -2)
t3 -> BLOCK    (timeLeft: 1993 | actionsLeft: -3)
t4 -> BLOCK    (timeLeft: 993 | actionsLeft: -4)
t5 -> BLOCK    (timeLeft: 996 | actionsLeft: -4)
t6 -> BLOCK    (timeLeft: 996 | actionsLeft: -4)
t7 -> BLOCK    (timeLeft: 996 | actionsLeft: -4)
t8 -> BLOCK    (timeLeft: 994 | actionsLeft: -4)
t9 -> BLOCK    (timeLeft: 993 | actionsLeft: -4)
```


Test code:
```
var RateLimiter = require("rolling-rate-limiter");
var Redis = require("redis");
var redisClient = Redis.createClient();

var limiter = RateLimiter({
  redis: redisClient,
  interval: 5000,
  maxInInterval: 1
});

var count = 0;
var check = function() {
  limiter('test', function(err, timeLeft, actionsLeft) {
    var result = 'UNKNOWN ';
    if (err) {
      result = 'ERROR   ';
    } else if (timeLeft) {
      result = 'BLOCK   ';
    } else {
      result = 'OK      ';
    }
    console.log('t' + (count++) + ' -> ' + result + ' (timeLeft: ' + timeLeft + ' | actionsLeft: ' + actionsLeft + ')');
  });
};

var foo = setInterval(check, 1000);
```

**Comment by janober** [comment]
@nonplus any input from your side? Because it seems like you made the change you proposed which I though would result in that issue to be fixed? At least your example output looked good.

**Comment by szdavid92** [comment]
@janober FWIW I created a lib based on this one, because this has some design flaws, one of which I think you are facing here:`timeLeft` is not correct, demonstrated by this simple example: in case of a 10 minute interval, 1 attempt / 10 minutes cap, and 10 actual attempts equally distributed in this interval, after inserting e.g. the last one will return timeLeft roughly around ~1 minute, however clearly you need to wait 10 minutes. Correctly implementing this requires a linear scan with the current data structure, which can make it practically unusable under certain loads. I resolved this with sampling. The reason I didn't do a PR is that  I needed other features anyways that required a complete rewrite.

**Comment by peterkhayes** [comment]
There is a new version of this library out. You can see the release notes [here](https://github.com/peterkhayes/rolling-rate-limiter#upgrading-from-01). I think it fixes some of these issues mentioned here.

If this behavior is important to you, you can use `wouldLimit` to first check if an action would be blocked. If it would not be, then you can call `limit` and ignore the result.
