### ISSUE TITLE
timeLeft wrong for minDifference

### ISSUE THREAD

**Issue by luckydonald** [peterkhayes/rolling-rate-limiter#26]
[The last change trying to fix it](https://github.com/classdojo/rolling-rate-limiter/commit/8b96a02c7426eb54bcca4f3e9eb324b4624300d4#diff-168726dbe96b3ce427e7fedce31bb0bcL64) changed the calculation to just return the [`minDifference`](https://github.com/classdojo/rolling-rate-limiter/blob/9693b68437ca6c81f4d803d589824be5c990232a/index.js#L69)

Shouldn't this be `minDifference - timeSinceLastRequest`?

If the last request was at say the at the time `900`,
and we specify the `minDifference=200`,
and we now have the time `now=1000`,
that results in `timeSinceLastRequest = 1000-900 = 100`.
Now we should wait 
`minDifference - timeSinceLastRequest = 200 - 100 = 100` more.

Means we would wait until `now + 100 = 1100`.

`900 + minDifference 200 = 1100`

**Comment by luckydonald** [comment]
As it is a one line change I could submit a PR, if wanted?

**Comment by luckydonald** [comment]
As it is a one line change I could submit a PR?

**Comment by peterkhayes** [comment]
https://github.com/classdojo/rolling-rate-limiter/pull/27

**Comment by peterkhayes** [comment]
Merged in and published as 0.1.10
