### ISSUE TITLE
Promisify rate limiter

### ISSUE THREAD

**Issue by weeco** [peterkhayes/rolling-rate-limiter#29]
Hey,
is it possible to use this rate limiter in a Promise based way? Usually I promisify libraries which use callbacks with bluebird, but I am not sure how I am supposed to do this here.

**Comment by peterkhayes** [comment]
Should be relatively straightforward:

```js
const limiter = Bluebird.promisify(RateLimiter(redisConfig))

limiter(userId)
  .then((timeLeft) => {
    /* 0 if unblocked, >0 if blocked; see readme */
  })
  .catch((err) => {
    /* handle redis error */ 
  })
```

**Comment by simlu** [comment]
+1

**Comment by delikat** [comment]
`util.promisify` also works here if you prefer native promises.

**Comment by peterkhayes** [comment]
There is a new version of this library out. You can see the release notes [here](https://github.com/peterkhayes/rolling-rate-limiter#upgrading-from-01). One of the changes is that all methods are promise-based now.
