### ISSUE TITLE
Get how many requests left

### ISSUE THREAD

**Issue by alexmccabe** [peterkhayes/rolling-rate-limiter#34]
Is there a way to get how many tokens the requesting IP address has left? I can see that it returns the timeLeft, but it would be useful to get the tokens too.

**Comment by peterkhayes** [comment]
There isn't currently, but I'd be open to a PR if you'd like to.  Probably just stick another method on the main rate limiter function.

**Comment by peterkhayes** [comment]
There is a new version of this library out. You can see the release notes [here](https://github.com/peterkhayes/rolling-rate-limiter#upgrading-from-01). It includes this functionality through the `limitWithInfo` or `wouldLimitWithInfo` methods.
