### ISSUE TITLE
limiter never frees up

### ISSUE THREAD

**Issue by rickyk586** [peterkhayes/rolling-rate-limiter#36]
```
const limiter = RateLimiter({
	redis: redisClient,
	maxInInterval: 2,
	interval: 1000 * 4
});

setInterval(() => {
	limiter('test', (err, timeLeft) => {
		if(err){
			throw err;
		}

		if(timeLeft){
			console.log(`timeLeft ${timeLeft}`);
			return;
		}

		console.log('good');
	});
}, 1000);
```

after exhausting 2, it continually shows timeLeft. I would expect it to free up a slot after 4 seconds.

**Comment by peterkhayes** [comment]
This is a design decision in the implementation, which is documented at the bottom of the readme:

> Note: if an action is blocked, it is still added to the set. This means that if a user is continually attempting actions more quickly than the allowed rate, all of their actions will be blocked until they pause or slow their requests.

The reason we do this is to maintain atomicity. The series of Redis commands that are executed can't include branching, and that means we can't skip adding an event to the set when a user was rate limited.

If this is a dealbreaker for you, there are likely other rate limiter implementations that you can use.

**Comment by peterkhayes** [comment]
There is a new version of this library out. You can see the release notes [here](https://github.com/peterkhayes/rolling-rate-limiter#upgrading-from-01).

If this behavior is important to you, you can use `wouldLimit` to first check if an action would be blocked. If it would not be, then you can call `limit` and ignore the result.
