### ISSUE TITLE
Time remaining calculated incorrectly

### ISSUE THREAD

**Issue by artursudnik** [peterkhayes/rolling-rate-limiter#40]
Hi,

While debugging this module to find the reason why time remaining is not calculated as expected I found that the last action is not taken into consideration. It is caused by the order of commands in a transaction when using the module with Redis: https://github.com/peterkhayes/rolling-rate-limiter/blob/29e480a73c7e0eaebe06d486e541e48beb5d9b8d/index.js#L52 
First, ZRANGE command is executed, and only after that ZADD command is executed. As a result, the last action is not included in the userSet, so the remaining calculations are incorrect.

Can you review my finding, please?

Artur

**Comment by peterkhayes** [comment]
Hi Artur - looks like you're right.

I recently made substantial changes to the library, which included fixing this issue. Check out the release notes [here](https://github.com/peterkhayes/rolling-rate-limiter#upgrading-from-01).
