### ISSUE TITLE
NPM package is published without .js files

### ISSUE THREAD

**Issue by ykrasik** [peterkhayes/rolling-rate-limiter#43]
The latest package is published with only the .ts files, making it challenging to consume from pure .js projects.
Also, while I haven't tried, I think this will cause issues with Typescript projects as well, as typescript is usually configured to not compile anything in node_modules.

**Comment by peterkhayes** [comment]
Ok, this should work. Published as `0.2.3`

**Comment by ykrasik** [comment]
Confirmed working, thanks for the quick response!
