### ISSUE TITLE
Trouble integrating into Typescript project

### ISSUE THREAD

**Issue by ykrasik** [peterkhayes/rolling-rate-limiter#44]
Hi, me again :)

This time I'm trying to integrate this into a Typescript project, and I ran into the following issues:
1. There are no type definition (`.d.ts`) files, only actual source files under `/src`. So the way to import it is to write `import {InMemoryRateLimiter, RateLimiterOptions} from 'rolling-rate-limiter/src'` which causes typescript to try to compile this file instead of just importing the type definitions.
2. The typescript compilation step above fails, because my devDependencies aren't prepared for it, and I have strict mode turned on which fails it even further for some places that have implicit 'any' types.

The best solution to this would be to include an `index.d.ts` in the root of the project that contains only type definitions.

**Comment by ykrasik** [comment]
Forget it, found the @types package.

**Comment by ykrasik** [comment]
Wait, its for v0.1.0. Sorry for the mess :)

**Comment by peterkhayes** [comment]
Let me take a look! I thought it was set up to generate a `.d.ts` file...

**Comment by peterkhayes** [comment]
Ok, this is fixed now in `0.2.6`.
