### ISSUE TITLE
Redis as a mandatory dependency

### ISSUE THREAD

**Issue by ykrasik** [peterkhayes/rolling-rate-limiter#45]
And again hello.

Now that a typing definition file is included, `ioredis` & `redis` are mandatory dependencies of the `index.d.ts` file.
For projects that don't have redis, like mine, this results in a compilation error by typescript. We use this lib as an in-memory throttler.

Maybe the solution here would be to provide 2 different typing files, one for in-memory and another for redis.

P.S. I noticed that the 2 redis libraries are defined as `devDependencies`. In my case this is good because I wouldn't want them pulled into my project transitively when I don't use them, but not sure if this is what you intended.

**Comment by peterkhayes** [comment]
Good flag! I'll look into this.

**Comment by peterkhayes** [comment]
As a temporary fix, could you install just `@types/redis` and `@types/ioredis`?

**Comment by peterkhayes** [comment]
Ok, I fixed this in `0.2.8`.

**Comment by ykrasik** [comment]
Apologies, been using this for a while but forgot to close this issue, works :)
