### ISSUE TITLE
How to consume multiple actions by calling limitWithInfo()? 

### ISSUE THREAD

**Issue by huksley** [peterkhayes/rolling-rate-limiter#58]
Hi, I would like to use for example 100 "actions" if possible and if not possible, use a smaller number available. How to implement that?

**Comment by peterkhayes** [comment]
I don't think that's supported at present, except by calling `limitWithInfo` inside a loop that bails if the limit is reached. This could be a useful feature if you're open to implementing something.

**Comment by huksley** [comment]
Ok, I'll try.
Btw have you seen this implementation?! This is terrible
https://github.com/ysulyma/microtime-nodejs/blob/master/index.js#L1

**Comment by peterkhayes** [comment]
As of this morning, that dependency is gone! Thanks @huksley 

https://github.com/peterkhayes/rolling-rate-limiter/pull/60
